import re

regexes_txt = {
    # Compnay internal domains
    "Internal Dev subdomain": re.compile('([a-z0-9]+[.]*[.]addyourDEVdomain[.]com)'),
    "Internal MGMT subdomain": re.compile('([a-z0-9]+[.]*[.]addyourMGMTdomain[.]com)'),
    "Internal PROD subdomain": re.compile('([a-z0-9]+[.]*[.]addyourPRODdomain[.]com)'),
    # Core keywords
    "Slack Token": re.compile('(xox(p|b|o|a)-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})'),
    "RSA private key": re.compile('BEGIN RSA PRIVATE KEY'),
    "SSH(OPENSSH) private key": re.compile('BEGIN OPENSSH PRIVATE KEY'),
    "SSH(DSA) private key": re.compile('BEGIN DSA PRIVATE KEY'),
    "SSH(EC) private key": re.compile('BEGIN EC PRIVATE KEY'),
    "PGP private key block": re.compile('BEGIN PGP PRIVATE KEY'),
    "Hacked by": re.compile('hacked by'),
    "Tor onion URI": re.compile('.*[.]onion'),
    # Credentials
    "Contains hardcoded username": re.compile('(?i)(db_)?(user|username)[\'|"]?\s*i?s?e?q?[!:=]+\s*[^{%()+$\\n\\r]+?.+?[\'|"]+?[^{%()+$\\n\\r]+?'),
    "Contains hardcoded password": re.compile('(?i)(pass|password)[\'|"]?\s*i?s?e?q?[!:=]+\s*[^{%()+$\\n\\r]+?.+?[\'|"]+?[^{%()+$\\n\\r]+?'),
    "Possible password leak": re.compile('\b([@a-zA-Z0-9._-]{5,})(:|\|)(.*)\b'),
    "Possible email leak": re.compile('[a-zA-Z0-9_.+-]+?@[a-zA-Z0-9-]+?\.[a-zA-Z0-9-.]+'),
    "Contains hardcoded credential": re.compile('(?i)credential[\'|"]?\s*i?s?e?q?[!:=]+\s*[^{%()+$\\n\\r]+?.+?[\'|"]+?[^{%()+$\\n\\r]+?'),
    "Contains hardcoded secret": re.compile('(?i)secret[\'|"]?\s*i?s?e?q?[!:=]+\s*[^{%()+$\\n\\r]+?.+?[\'|"]+?[^{%()+$\\n\\r]+?'),
    "Facebook Oauth": re.compile('(?i)facebook.*[\'|"][0-9a-f]{32}[\'|"]'),
    "Twitter Oauth": re.compile('(?i)twitter.*[\'|"][0-9a-zA-Z]{35,44}[\'|"]'),
    "GitHub": re.compile('(?i)github.*[[\'|"]0-9a-zA-Z]{35,40}[\'|"]'),
    "Google Oauth": re.compile('("(?i)client_secret":"[a-zA-Z0-9-_]{24}")'),
    "AWS API Key": re.compile('AKIA[0-9A-Z]{16}'),
    "Google API Key": re.compile('\bAIza.{35}\b'),
    "API Key hash32": re.compile('\b[a-fA-F\d]{32}\b'),
    "API Key hash64": re.compile('\b[a-fA-F\d]{64}\b'),
    "Heroku API Key": re.compile('[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}'),
    "Generic Secret": re.compile('(?i)secret.*[\'|"][0-9a-zA-Z]{32,45}[\'|"]'),
    # Database sensitive data
    "Database connection string": re.compile('\b(mongodb|http|https|ftp|mysql|postgresql|oracle)://(\S*):(\S*)@(\S*)\b'),
    "DML: GRANT ALL PRIVILEGES": re.compile('GRANT ALL PRIVILEGES'),
    "DML: IDENTIFIED BY": re.compile('IDENTIFIED BY'),
    "DML: GRANT SELECT": re.compile('GRANT SELECT'),
    "DML: CREATE USER": re.compile('CREATE USER'),
    # Php obfuscation
    "Php: dangerous function eval": re.compile('eval\('),
    "Php: dangerous function gzinflate": re.compile('gzinflate\('),
    "Php: dangerous function base64_decode": re.compile('base64_decode\('),
    "Php: dangerous function base64_decode in HEX": re.compile('\\142\\x61\\163\\145\\x36\\x34\\137\\144\\x65\\x63\\x6f\\x64\\x65'),
    "Php: dangerous function str_rot13": re.compile('str_rot13\(')
}

regexes_fs = {
    # Application config files
    "File: SQL dump file": re.compile('\S+\.sql(dump)?'),
    "Sequel Pro MySQL database manager bookmark file": re.compile('Favorites.plist'),
    "MySQL client command history file": re.compile('.?mysql_history'),
    "PostgreSQL client command history file": re.compile('.?psql_history'),
    "PostgreSQL password file": re.compile('.?pgpass'),
    "SSH configuration file": re.compile('.?ssh/config'),
    "Pidgin OTR private key": re.compile('otr.private_key'),
    "Shell command history file": re.compile('.?(bash_|zsh_|z)?history'),
    "Ruby IRB console history file": re.compile('.?irb_history'),
    "Recon-ng web reconnaissance framework API key database": re.compile('.?recon-ng/keys\.db'),
    "S3cmd configuration file": re.compile('.?s3cfg'),
    # "Files with private keys": re.compile('private.*key'),
    "AWS CLI credentials file": re.compile('.?aws/credentials'),
    "T command-line Twitter client configuration file": re.compile('.?trc'),
    "OpenVPN client configuration file": re.compile('ovpn'),
    "Shell configuration file": re.compile('.?(bash|zsh)rc'),
    "Shell profile configuration file": re.compile('.?(bash_|zsh_)?profile$'),
    "Shell command alias configuration file": re.compile('.?(bash_|zsh_)?aliases$'),
    "Ruby On Rails secret token configuration file": re.compile('secret_token\.rb$'),
    "Ruby On Rails database schema file": re.compile('schema\.rb$'),
    "Potential Ruby On Rails database configuration file": re.compile('database\.yml$'),
    "Django configuration file": re.compile('settings\.py$'),
    "PHP configuration file": re.compile('(.*)?config\.(inc|php)$'),
    "KeePass password manager database file": re.compile('kdb'),
    "1Password password manager database file": re.compile('agilekeychain'),
    "Apple Keychain database file": re.compile('keychain$'),
    "GNOME Keyring database file": re.compile('key(store|ring)$'),
    "Log file": re.compile('\w+\.log$'),
    "Network traffic capture file": re.compile('pcap$'),
    "GnuCash database file": re.compile('gnucash$'),
    "Contains word: backup": re.compile('(?!.*(py|sh|php|rb)$)(?=.*backup[^/]*)^(.*)'),
    "Contains word: dump": re.compile('(?!.*(py|sh|php|rb)$)(?=.*dump[^/]*)^(.*)'),
    "Jenkins publish over SSH plugin file": re.compile('jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml'),
    "Potential Jenkins credentials file": re.compile('credentials\.xml$'),
    "Apache htpasswd file": re.compile('.?htpasswd$'),
    "Configuration file for auto-login process": re.compile('(\.|_)?netrc$'),
    "KDE Wallet Manager database file": re.compile('kwallet$'),
    "Potential MediaWiki configuration file": re.compile('(?i)LocalSettings\.php$'),
    "Tunnelblick VPN configuration file": re.compile('tblk'),
    "Rubygems credentials file": re.compile('.?gem/credentials'),
    "Potential MSBuild publish profile": re.compile('.*\.pubxml(\.user)?'),
    "Little Snitch firewall configuration file": re.compile('configuration.user.xpl'),
    "Day One journal file": re.compile('dayone'),
    "Potential jrnl journal file": re.compile('journal.txt'),
    "Tugboat DigitalOcean management tool configuration": re.compile('.?tugboat'),
    "git-credential-store helper credentials file": re.compile('.?git-credentials'),
    "Git configuration file": re.compile('.?gitconfig'),
    "Chef Knife configuration file": re.compile('knife.rb'),
    "Chef private key": re.compile('.?chef/(.*)\.pem'),
    "cPanel backup ProFTPd credentials file": re.compile('proftpdpasswd'),
    "Robomongo MongoDB manager configuration file": re.compile('robomongo.json'),
    "FileZilla FTP configuration file": re.compile('filezilla.xml'),
    "FileZilla FTP recent servers file": re.compile('recentservers.xml'),
    "Ventrilo server configuration file": re.compile('ventrilo_srv.ini'),
    "Docker configuration file": re.compile('.?dockercfg'),
    "NPM configuration file": re.compile('.?npmrc'),
    "Terraform variable config file": re.compile('terraform.tfvars'),
    "Environment configuration file": re.compile('.?env'),
    "Potential cryptographic private key pem": re.compile('pem'),
    "Potential cryptographic private key": re.compile('private.*key(pair)?'),
    "Potential cryptographic key bundle ": re.compile('(pkcs12|pfx|p12|asc)'),
    "Private SSH key": re.compile('.*_(rsa|dsa|ed25519|ecdsa)'),
    "Pidgin chat client account configuration file": re.compile('.?purple/accounts\.xml'),
    "Hexchat/XChat IRC client server list configuration file": re.compile('.?xchat2?/servlist_?\.conf'),
    "Irssi IRC client configuration file": re.compile('.?irssi/config'),
    "DBeaver SQL database manager configuration file": re.compile('.?dbeaver-data-sources.xml'),
    "Mutt e-mail client configuration file": re.compile('.?muttrc'),
    "OmniAuth configuration file": re.compile('omniauth\.rb'),
    "Carrierwave configuration file": re.compile('carrierwave\.rb'),
    "Well, this is awkward... Gitrob configuration file": re.compile('.?gitrobrc')
}

regexes_txt_raw = {
    # Compnay internal domains
    "Internal DEV subdomain": '([a-z0-9]+[.]*[.]addyourDEVdomain[.]com)',
    "Internal MGMT subdomain": '([a-z0-9]+[.]*[.]addyourMGMTdomain[.]com)',
    "Internal PROD subdomain": '([a-z0-9]+[.]*[.]addyourPRODdomain[.]com)',
    # Core keywords
    "Slack Token": '(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})',
    "RSA private key": 'BEGIN RSA PRIVATE KEY',
    "SSH(OPENSSH) private key": 'BEGIN OPENSSH PRIVATE KEY',
    "SSH(DSA) private key": 'BEGIN DSA PRIVATE KEY',
    "SSH(EC) private key": 'BEGIN EC PRIVATE KEY',
    "PGP private key block": 'BEGIN PGP PRIVATE KEY',
    "Hacked by": 'hacked by',
    "Tor onion URI": '.*[.]onion',
    # Credentials
    "Contains word username": '(?i)(db_)?(user(name)?|usrname)[\'|"]?\s*?[:=,]+\s*[\'|"]+[^{]+?\S+?[^}][\'|"]',
    "Contains word: password": '(?i)pass(word)?[\'|"]?\s*?[:=,]+\s*[\'|"]+[^{]+?\S+?[^}][\'|"]',
    "Possible password leak": '\b([@a-zA-Z0-9._-]{5,})(:|\|)(.*)\b',
    "Possible email leak": '[a-zA-Z0-9_.+-]+?@[a-zA-Z0-9-]+?\.[a-zA-Z0-9-.]+',
    "Contains word: credential": '(?i)credential?\s*[:=,]+\s*?[\'|"].*?[\'|"]',
    "Contains word: secret": '(?i)sec(ret)?\s*?=\s*?[\'|"].*?[\'|"]',
    "Facebook Oauth": '(?i)facebook.*[\'|"][0-9a-f]{32}[\'|"]',
    "Twitter Oauth": '(?i)twitter.*[\'|"][0-9a-zA-Z]{35,44}[\'|"]',
    "GitHub": '(?i)github.*[[\'|"]0-9a-zA-Z]{35,40}[\'|"]',
    "Google Oauth": '("(?i)client_secret":"[a-zA-Z0-9-_]{24}")',
    "AWS API Key": 'AKIA[0-9A-Z]{16}',
    "Google API Key": '\bAIza.{35}\b',
    "API Key hash32": '\b[a-fA-F\d]{32}\b',
    "API Key hash64": '\b[a-fA-F\d]{64}\b',
    "Heroku API Key": '[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}',
    "Generic Secret": '(?i)secret.*[\'|"][0-9a-zA-Z]{32,45}[\'|"]',
    # Database sensitive data
    "Database connection string": '\b(mongodb|http|https|ftp|mysql|postgresql|oracle):\/\/(\S*):(\S*)@(\S*)\b',
    "DML: GRANT ALL PRIVILEGES": 'GRANT ALL PRIVILEGES',
    "DML: IDENTIFIED BY": 'IDENTIFIED BY',
    "DML: GRANT SELECT": 'GRANT SELECT',
    "DML: CREATE USER": 'CREATE USER',
    # Php obfuscation
    "Php: dangerous function eval": 'eval\(',
    "Php: dangerous function gzinflate": 'gzinflate\(',
    "Php: dangerous function base64_decode": 'base64_decode\(',
    "Php: dangerous function base64_decode HEX": '\\142\\x61\\163\\145\\x36\\x34\\137\\144\\x65\\x63\\x6f\\x64\\x65',
    "Php: dangerous function str_rot13": 'str_rot13\('
}

regexes_fs_raw = {
    # Application config files
    "File: SQL dump file": 'sql(dump)?',
    "Sequel Pro MySQL database manager bookmark file": 'Favorites.plist',
    "MySQL client command history file": '.?mysql_history',
    "PostgreSQL client command history file": '.?psql_history',
    "PostgreSQL password file": '.?pgpass',
    "SSH configuration file": '.?ssh/config',
    "Pidgin OTR private key": 'otr.private_key',
    "Shell command history file": '.?(bash_|zsh_|z)?history',
    "Ruby IRB console history file": '.?irb_history',
    "Recon-ng web reconnaissance framework API key database": '.?recon-ng\/keys\.db',
    "S3cmd configuration file": '.?s3cfg',
    # "Files with private keys": 'private.*key',
    "AWS CLI credentials file": '.?aws/credentials',
    "T command-line Twitter client configuration file": '.?trc',
    "OpenVPN client configuration file": 'ovpn',
    "Shell configuration file": '.?(bash|zsh)rc',
    "Shell profile configuration file": '.?(bash_|zsh_)?profile',
    "Shell command alias configuration file": '.?(bash_|zsh_)?aliases',
    "Ruby On Rails secret token configuration file": 'secret_token\.rb',
    "Ruby On Rails database schema file": 'schema\.rb',
    "Potential Ruby On Rails database configuration file": 'database\.yml',
    "Django configuration file": 'settings\.py',
    "PHP configuration file": '(.*)?config(\.inc)?\.php',
    "KeePass password manager database file": 'kdb',
    "1Password password manager database file": 'agilekeychain',
    "Apple Keychain database file": 'keychain',
    "GNOME Keyring database file": 'key(store|ring)',
    "Log file": 'log',
    "Network traffic capture file": 'pcap',
    "GnuCash database file": 'gnucash',
    "Contains word: backup": 'backup',
    "Contains word: dump": 'dump',
    "Jenkins publish over SSH plugin file": 'jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml',
    "Potential Jenkins credentials file": 'credentials.xml',
    "Apache htpasswd file": '.?htpasswd',
    "Configuration file for auto-login process": '(\.|_)?netrc',
    "KDE Wallet Manager database file": 'kwallet',
    "Potential MediaWiki configuration file": 'LocalSettings\.php',
    "Tunnelblick VPN configuration file": 'tblk',
    "Rubygems credentials file": '.?gem/credentials',
    "Potential MSBuild publish profile": '.*\.pubxml(\.user)?',
    "Little Snitch firewall configuration file": 'configuration.user.xpl',
    "Day One journal file": 'dayone',
    "Potential jrnl journal file": 'journal.txt',
    "Tugboat DigitalOcean management tool configuration": '.?tugboat',
    "git-credential-store helper credentials file": '.?git-credentials',
    "Git configuration file": '.?gitconfig',
    "Chef Knife configuration file": 'knife.rb',
    "Chef private key": '.?chef/(.*)\.pem',
    "cPanel backup ProFTPd credentials file": 'proftpdpasswd',
    "Robomongo MongoDB manager configuration file": 'robomongo.json',
    "FileZilla FTP configuration file": 'filezilla.xml',
    "FileZilla FTP recent servers file": 'recentservers.xml',
    "Ventrilo server configuration file": 'ventrilo_srv.ini',
    "Docker configuration file": '.?dockercfg',
    "NPM configuration file": '.?npmrc',
    "Terraform variable config file": 'terraform.tfvars',
    "Environment configuration file": '.?env',
    "Potential cryptographic private key pem": 'pem',
    "Potential cryptographic private key": 'private.*key(pair)?',
    "Potential cryptographic key bundle": '(pkcs12|pfx|p12|asc)',
    "Private SSH key": '.*_(rsa|dsa|ed25519|ecdsa)',
    "Pidgin chat client account configuration file": '.?purple\/accounts\.xml',
    "Hexchat/XChat IRC client server list configuration file": '.?xchat2?\/servlist_?\.conf',
    "Irssi IRC client configuration file": '.?irssi\/config',
    "DBeaver SQL database manager configuration file": '.?dbeaver-data-sources.xml',
    "Mutt e-mail client configuration file": '.?muttrc',
    "OmniAuth configuration file": 'omniauth\.rb',
    "Carrierwave configuration file": 'carrierwave\.rb',
    "Well, this is awkward... Gitrob configuration file": '.?gitrobrc'
}
